# Generated by Django 3.2.25 on 2025-01-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_employee_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
        migrations.AddField(
            model_name="department",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
