# Generated by Django 3.2.25 on 2025-01-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_auto_20250123_0858"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.CharField(
                default="example@example.com",
                help_text="The email of the employee.",
                max_length=50,
            ),
        ),
    ]
