# Generated by Django 3.2.25 on 2025-01-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_employee_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="age",
            field=models.PositiveIntegerField(
                default=25, help_text="The age of the employee."
            ),
        ),
    ]
