# Generated by Django 5.1.6 on 2025-02-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0008_employee_user_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="user",
        ),
        migrations.AddField(
            model_name="employee",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="password",
            field=models.CharField(
                default="password123", max_length=128, verbose_name="password"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(
                default="example@example.com",
                help_text="The email of the employee.",
                max_length=50,
                unique=True,
            ),
        ),
    ]
