# Generated by Django 5.1.6 on 2025-02-21 07:49

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0009_remove_employee_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="employee",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
