# Generated by Django 5.1.6 on 2025-02-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0010_alter_employee_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="employee",
            managers=[],
        ),
    ]
