# Generated by Django 5.1.6 on 2025-02-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0011_alter_employee_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
