# Generated by Django 5.1.6 on 2025-02-21 08:44

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0013_employee_groups_employee_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="employee",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
