# Generated by Django 5.1.6 on 2025-02-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0014_alter_employee_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelManagers(
            name="employee",
            managers=[],
        ),
    ]
