[pytest]
pythonpath = ./employee_management
DJANGO_SETTINGS_MODULE = employee_management.settings.test
python_files = tests.py test_*.py *_tests.py
; filterwarnings =
;     ignore::django.utils.deprecation.RemovedInDjango50Warning
; addopts =
;   # run parallel in 4 CPUs
;   -n4
;   --reuse-db
;   --no-migrations
;   --trace
;   --capture=fd
;   -ra
;   #--cov=. --cov-report=html --cov-report=term-missing -v
; markers =
;   now: marks tests as now (@pytest.mark.now) to run (deselect with '-m "not now"', run with "-sv -m now")